[package]
name = "twine-solana-programs" 
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "twine_chain",
    "tokens_gateway"
]

[workspace.dependencies]
hex = "0.4.3"
sha3="0.10.8"
borsh = "0.10"
thiserror = "1.0.63"
solana-bn254 = "2.1.6"
num-traits = "0.2"
base64ct = "=1.6.0"
num-bigint = "0.4.6"
solana-program = "1.18.26"
solana-secp256k1-recover = "2.1.6"


tokio = { version = "1.0", features = ["macros", "rt"], default-features = false }
libsecp256k1 = { version = "0.7.1", default-features = false }
sp1-solana = { git = "https://github.com/succinctlabs/sp1-solana" }
spl-token = {version = "3.5.0", default-features = false, features = ["no-entrypoint"] }
tokens_gateway = { path = "./tokens_gateway", features = ["no-entrypoint"] }
twine_chain = { path = "./twine_chain", features = ["no-entrypoint"] }

[dev-dependencies]
sha3 = { workspace = true }
dirs = "5"
tokio-test = "0.4"
test-case = "3.3"
solana-sdk = "1.18.26"
solana-program-test = "1.18.26"
borsh = { workspace = true }
solana-program = { workspace = true }
tokens_gateway = { workspace = true }
twine_chain = { workspace = true }