[package]
name = "tokens_gateway"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["."]

[dependencies]
hex = "0.4"
sha3 = "0.10"
borsh = "0.10.3"
thiserror = "1.0"
num-traits = "0.2" 
spl-token = "3.5.0"
num-bigint = "0.4.3"
solana-program = "1.18.26"
solana-secp256k1-recover = "2.1.6"
libsecp256k1 = { version = "0.7.1", features = ["std"] }
twine_chain = { path = "../twine_chain" }
sp1-solana = { git = "https://github.com/succinctlabs/sp1-solana" }