[package]
name = "oapp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "oapp"

[features]
no-entrypoint = []
custom-heap = []
custom-panic = []

[dependencies]
solana-program           = { workspace = true }
borsh                    = { workspace = true }
thiserror                = { workspace = true }

